# This publish a package to NPM Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish Package

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  publish-npm:
    if: github.repository == 'GrimLink/eleventy-plugin-lucide-icons'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: https://registry.npmjs.org/
          always-auth: true

      - run: npm ci

      - run: npm publish --access public
